Fix project build.
WrenSecurity/wrenig pull request #1
Opened 2023-12-20 12:01 UTC by karelmaxa

This PR fixes build of the project. The following significant changes have been performed:

* Switch to the latest releases of the `wrensec-parent` and `wrensec-commons`.
* Fixed the UI build (including switching to the latest release of the `wrensec-ui`).
* Cleaned up all POM files.
* Fixed tests after Mockito upgrade.
* Introduced Docker build.

2023-12-20 14:48 UTC, pavelhoral requested changes
Just a few minor nitpicks.

2023-12-21 12:42 UTC, karelmaxa commented on Dockerfile
> +  CATALINA_OPTS="-server -Xmx1g"
Changed.

2023-12-21 12:45 UTC, karelmaxa commented on openig-core/pom.xml
> +            <artifactId>ivy</artifactId>
Actually, I don't know. There is probably no use case at the moment. I have removed the Ivy dependency and everything seems to work fine.

2023-12-21 13:39 UTC, pavelhoral approved these changes
LGTM

2023-12-21 13:39 UTC, merged